---
- name: Use /Applications for MacOS < 10.15
  set_fact:
    dockitems_enabled: "{{ dockitems_enabled_pre_10_15 }}"
  when: ansible_distribution_version is version('10.15', '<')

- name: Use /System/Applications for MacOS >= 10.15
  set_fact:
    dockitems_enabled: "{{ dockitems_enabled_post_10_15 }}"
  when: ansible_distribution_version is version('10.15', '>=')

- name: clear the dock
  include_role:
    name: fubarhouse.macdock
