---
- name: Never Sleep Mode
  command: "{{ item }}"
  with_items:
    - systemsetup -setsleep Never
    - systemsetup -setharddisksleep Never
    - systemsetup -setcomputersleep Never
    - systemsetup -setdisplaysleep Never
  changed_when: false
  become: true

- name: Additiona cleanups for never sleep mode
  include_role:
    name: feffi.macos-standby
  vars:
    standby_delay: false
    hibernate_mode: 0
    remove_sleepimage: true

