---
- name: Never Sleep Mode
  command: "{{ item }}"
  with_items:
    - systemsetup -setsleep Never
    - systemsetup -setharddisksleep Never
    - systemsetup -setcomputersleep Never
    - systemsetup -setdisplaysleep Never
    - pmset -a standbydelay 0
    - pmset -a displaysleep 0
    - pmset -a disablesleep 1
    - pmset -a disksleep 0
    - pmset -a hibernatemode 0
  changed_when: false
  become: true
